import{a as b,S as v,i}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&f(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const S="54653333-1a4d24954eec451e3cf04620f",q="https://pixabay.com/api/";async function u(e,r){return(await b.get(q,{params:{key:S,q:e,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}u().then(e=>{console.log(e)}).catch(e=>{console.log(e)});const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),a=document.querySelector(".js-load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){const r=e.map(o=>`
        <li class="gallery-item">
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <div class="info">
            <p>Likes <span>${o.likes}</span></p>
            <p>Views <span>${o.views}</span></p>
            <p>Comments <span>${o.comments}</span></p>
            <p>Downloads <span>${o.downloads}</span></p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){m.innerHTML=""}function y(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}function B(){a.classList.remove("load-more-hidden"),a.classList.add("load-more")}function L(){a.classList.remove("load-more"),a.classList.add("load-more-hidden")}const O=document.querySelector(".js-load-more"),P=document.querySelector(".form");let l=1,w="",n=0,d=0;P.addEventListener("submit",x);O.addEventListener("click",E);function x(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(w=r,n=0,l=1,!r){i.show({message:"Please enter a search query",color:"red"});return}$(),y(),u(r,l).then(o=>{d=o.totalHits,n=o.hits.length,h(o.hits),n>=d?(L(),i.show({message:"We're sorry, but you've reached the end of search results.",color:"blue"})):B()}).finally(()=>g())}async function E(){l++,y();try{const e=await u(w,l);h(e.hits),H(),n+=e.hits.length,n>=d&&(L(),i.show({message:"We're sorry, but you've reached the end of search results.",color:"blue"}))}finally{g()}}function H(){const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
