import{a as v,S,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))f(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&f(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const q="54653333-1a4d24954eec451e3cf04620f",M="https://pixabay.com/api/";async function m(e,r){return(await v.get(M,{params:{key:q,q:e,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}m().then(e=>{console.log(e)}).catch(e=>{console.log(e)});const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),l=document.querySelector(".js-load-more");let P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const r=e.map(t=>`
        <li class="gallery-item">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <div class="info">
            <p>Likes <span>${t.likes}</span></p>
            <p>Views <span>${t.views}</span></p>
            <p>Comments <span>${t.comments}</span></p>
            <p>Downloads <span>${t.downloads}</span></p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",r),P.refresh()}function $(){h.innerHTML=""}function g(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function w(){l.classList.remove("load-more-hidden"),l.classList.add("load-more")}function c(){l.classList.remove("load-more"),l.classList.add("load-more-hidden")}const B=document.querySelector(".form"),H=document.querySelector(".js-load-more");let i=1,b="",n=0,u=0;B.addEventListener("submit",O);H.addEventListener("click",x);async function O(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(b=r,i=1,n=0,!r){a.show({message:"Please enter a search query",color:"red"});return}$(),c(),g();try{const t=await m(r,i);if(t.totalHits===0){a.show({message:"No images found. Try another query.",color:"blue"});return}u=t.totalHits,n=t.hits.length,y(t.hits),n<u?w():(c(),a.show({message:"You've reached the end of search results.",color:"blue"}))}catch{a.show({message:"Something went wrong. Please try again later.",color:"red"})}finally{L()}}async function x(){i++,c(),g();try{const e=await m(b,i);y(e.hits),E(),n+=e.hits.length,n>=u?(c(),a.show({message:"You've reached the end of search results.",color:"blue"})):w()}catch{a.show({message:"Something went wrong. Please try again later.",color:"red"})}finally{L()}}function E(){const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
